data-dir: /Users/heades/teaching/CSCI-3300/website

from: markdown+emoji

to: html

template: layouts/site

output-file: 

input-files: []

standalone: true

self-contained: false

highlight-style: pygments

email-obfuscation: javascript
metadata:
  email: harley.eades@gmail.com

html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

css:
- "/plweb/includes/css/default.css"
